routes/web.php
<?php

use Illuminate\Support\Facades\Route;
use App\Http\Controllers\AdminController;
use App\Http\Controllers\BarangController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
//transaksi
Route::get('/', [AdminController::class, 'index']);
Route::post('/', [AdminController::class, 'store']);
Route::get('/transaksi/{transaksi}/edit', [AdminController::class, 'edit']);
Route::delete('/transaksi/{transaksi}', [AdminController::class, 'destroy']);
Route::patch('/transaksi/{transaksi}', [AdminController::class, 'update']);
Route::get('/sort/{transaksi}', [AdminController::class, 'sorting']);

//barang
Route::get('/barang', [BarangController::class, 'index']);
Route::post('/barang', [BarangController::class, 'store']);
Route::get('/barang/{barang}/edit', [BarangController::class, 'edit']);
Route::delete('/barang/{barang}', [BarangController::class, 'destroy']);
Route::patch('/barang/{barang}', [BarangController::class, 'update']);
Route::get('/barang/{barang}', [BarangController::class, 'show']);
Route::get('/transaksi/barang', [BarangController::class, 'transaksi']);

app/Http/Controllers/BarangController.php
<?php

namespace App\Http\Controllers;

use App\Models\Barang;
use App\Models\Transaksi;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\DB;

class BarangController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        if ($request->nama != NULL) {
            $barang = Barang::where('nama', 'like',"%".$request->nama."%")
            ->paginate(10);
        } else {
            $barang = Barang::paginate(10);
        }
        
        return view('content.barang', compact('barang'));
    }

    public function transaksi(Request $request)
    {
        $from = $request->from;
        $until = $request->until;
        $barang = Barang::join('transaksis', 'transaksis.barang_id', '=', 'barangs.id')
                ->groupBy('transaksis.barang_id')
                ->selectRaw('barangs.nama, barangs.stok , sum(jumlah_terjual) as sum')
                ->withCount('transaksi')
                ->whereBetween('tanggal_transaksi', [$from, $until])
                ->orderBy('sum', 'desc')
                ->paginate(20);
        
        
        return view('content.transaksiBarang', compact('barang', 'from', 'until'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $barang = new Barang;
        $barang->nama = $request->nama;
        $barang->stok = $request->stok;
        $barang->jenis_barang = $request->jenis_barang;
        $barang->save();
        return redirect('/barang')->with('message', 'Data berhasil ditambahkan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $barang = Barang::find($id);
        return view('content.showBarang', compact('barang'));
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $barang = Barang::find($id);
        $jenis = [
            '1' => 'konsumsi',
            '2' => 'pembersih'
        ];
        return view('content.editBarang', compact('barang', 'jenis'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $barang = Barang::find($id);
        $barang->nama = $request->nama;
        $barang->stok = $request->stok;
        $barang->jenis_barang = $request->jenis_barang;
        $barang->save();
        return redirect('/barang')->with('message', 'Data berhasil ditambahkan');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        Barang::destroy($id);
        return redirect('/barang')->with('message', 'Data berhasil dihapus');
    }
}

resources/views/content/barang.blade.php
@extends('template.master')
@section('title')
    Warehouse 
@endsection
@section('subTitle')
    Data Barang di toko XYZ
@endsection
@section('content')

<div class="row justify-content-md-center border-bottom mb-3 pb-3" >
  <div class="col-auto">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Tambah Data Baru
    </button>
  </div>
  
  <div class="col-auto">
    <form action="/barang" method="GET">
      <div class="input-group">
          <input name="nama" class="form-control" type="text" placeholder="Cari barang..." aria-label="Search for..." aria-describedby="btnNavbarSearch" />
          <button class="btn btn-primary" id="btnNavbarSearch" type="submit"><i class="fas fa-search"></i></button>
      </div>
  </form>
  </div>
  
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
          <tr>
            <th scope="col">#</th>            
            <th scope="col">nama barang</th>
            <th scope="col">Stok</th>
            <th scope="col">Jenis Barang</th>
            <th scope="col">Action</th>
            
          </tr>
        </thead>
        <tbody>
            @foreach ($barang as $item)
            <tr>
                <th scope="row">{{ $loop->iteration }}</th>
                <td>{{$item->nama}}</td>
                <td>{{$item->stok}}</td>
                <td>{{$item->jenis_barang}}</td>
                <td><a class="badge bg-success" href="barang/{{$item->id}}/edit">Edit</a>
                  <form action="/barang/{{$item->id}}" method="POST" class="d-inline">
                    @csrf 
                    <input type="hidden" name="_method" value="delete">
                    <button type="submit" class="badge bg-danger">Hapus</button></form> 
                  
                    
                  </td>
              </tr>
            @endforeach
        </tbody>
  </table>
  </div>
</div>
<div class="row">
  <div class="col-12 mt-3">
    {{ $barang->links() }}
  </div>
  
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Data baru</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {{-- form --}}
        <form action="/barang" method="POST">
          @csrf
          <div class="mb-3">
            <label for="nama" class="form-label">Nama Barang</label>
            <input type="text" class="form-control" name="nama" id="nama" required>
          </div>
          
          <div class="mb-3">
            <label for="stok" class="form-label">Stok</label>
            <input type="number" class="form-control" id="stok" name="stok" required>
          </div>

          <div class="mb-3">
            <label for="jenis_barang" class="form-label">Jenis Barang</label>
            <select name="jenis_barang" id="jenis_barang" class="form-control" required>
              <option value="">Pilih Jenis Barang</option>
              <option value="1">Konsumsi</option>
              <option value="2">Pembersih</option>
            </select>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
    </div>
  </div>
</div>
    
@endsection

resources/views/content/dashboard.blade.php
@extends('template.master')
@section('title')
    Dashboard 
@endsection
@section('subTitle')
    Data Penjualan Toko XYZ tahun 2021
@endsection
@section('content')
<div class="row justify-content-md-center border-bottom mb-3 pb-3" >
  <div class="col-auto">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
      Tambah Transaksi Baru
    </button>
  </div>
  <div class="col-auto">
    <!-- Button trigger modal -->
    <button type="button" class="btn btn-success" data-bs-toggle="modal" data-bs-target="#transaksiBarang">
      Banyak Transaksi per Barang
    </button>
  </div>
  <div class="col-auto">
    <form action="/" method="GET">
      <div class="input-group">
          <input name="tanggal_transaksi" class="form-control" type="date" placeholder="Cari transaksi" aria-label="Search for..." aria-describedby="btnNavbarSearch" />
          <button class="btn btn-primary" id="btnNavbarSearch" type="submit"><i class="fas fa-search"></i></button>
      </div>
  </form>
  </div>
  
</div>
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
          <tr>
            <th scope="col">#</th>
            @foreach ($sort as $key => $value)
            <th scope="col"><a href="/sort/{{$key}}">{{$value}}  </a> </th>
            @endforeach
            
            <th scope="col">Jumlah Terjual</th>
            <th scope="col">Jenis Barang</th>
            <th scope="col">Action</th>
            
          </tr>
        </thead>
        <tbody>
            @foreach ($transaksi as $item)
            <tr>
                <th scope="row">{{ $loop->iteration }}</th>
                <td>{{$item->tanggal_transaksi}}</td>
                <td> <a href="/barang/{{$item->barang_id}}">{{$item->barang->nama}}</a> </td>
                <td>{{$item->jumlah_terjual}}</td>
                <td>{{$item->barang->jenis_barang}}</td>
                <td><a class="badge bg-success" href="transaksi/{{$item->id}}/edit">Edit</a>
                  <form action="/transaksi/{{$item->id}}" method="POST" class="d-inline">
                    @csrf 
                    <input type="hidden" name="_method" value="delete">
                    <button type="submit" class="badge bg-danger">Hapus</button></form> 
                  
                    
                  </td>
              </tr>
            @endforeach
        </tbody>
  </table>
  
  </div>
</div>
<div class="row">
  <div class="col-12 mt-3">
    {{ $transaksi->links() }}
  </div>
  
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Transaksi baru</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {{-- form --}}
        <form action="/" method="POST">
          @csrf
          <div class="mb-3">
            <label for="transaksi" class="form-label">Tanggal Transaksi</label>
            <input type="date" class="form-control" name="tanggal_transaksi" id="transaksi" required>
          </div>
          <div class="mb-3">
            <label for="barang" class="form-label">Pilih barang</label>
            <select name="barang_id" id="barang" class="form-control" required>
              <option value="">Pilih barang</option>
              @foreach ($barang as $item)
              <option value="{{$item->id}}">{{$item->nama}}</option>
              @endforeach
            </select>
          </div>
          <div class="mb-3">
            <label for="jumlah" class="form-label">Jumlah Terjual</label>
            <input type="number" class="form-control" id="jumlah" name="jumlah_terjual" required>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="transaksiBarang" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Jumlah Transaksi per barang</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {{-- form --}}
        <form action="/transaksi/barang" method="GET">
          @csrf
          <div class="mb-3">
            <label for="from" class="form-label">Dari Tanggal</label>
            <input type="date" class="form-control" name="from" id="from" required>
          </div>
          <div class="mb-3">
            <label for="until" class="form-label">Hingga Tanggal</label>
            <input type="date" class="form-control" name="until" id="until" required>
          </div>
          
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
    </div>
  </div>
</div>
    
@endsection

resources/views/content/edit.blade.php
@extends('template.master')
@section('title')
    Edit Data Penjualan
@endsection
@section('subTitle')
    Silahkan Masukkan data yang ingin di edit
@endsection
@section('content')

<div class="row">
  <div class="col-md-6">
    <form action="/transaksi/{{$data->id}}" method="POST">
      @csrf
      <input type="hidden" name="_method" value="patch">
      <div class="mb-3">
        <label for="transaksi" class="form-label">Tanggal Transaksi</label>
        <input type="date" class="form-control" name="tanggal_transaksi" id="transaksi" value="{{$data->tanggal_transaksi}}">
      </div>
      <div class="mb-3">
        <label for="barang" class="form-label">Pilih barang</label>
        <select name="barang_id" id="barang" class="form-control" >
          <option value="">Pilih barang</option>
          @foreach ($barang as $item)
            @if ($item->id == $data->barang_id)
              <option value="{{$item->id}}" selected>{{$item->nama}}</option>
            @else
              <option value="{{$item->id}}">{{$item->nama}}</option>
            @endif
          @endforeach
        </select>
      </div>
      <div class="mb-3">
        <label for="jumlah" class="form-label">Jumlah Terjual</label>
        <input type="number" class="form-control" id="jumlah" name="jumlah_terjual" value="{{$data->jumlah_terjual}}">
      </div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Save changes</button>
  </div>
</form>
  </table>
  </div>
</div>


    
@endsection

resources/views/content/editBarang.blade.php
@extends('template.master')
@section('title')
    Edit Data Penjualan
@endsection
@section('subTitle')
    Silahkan Masukkan data yang ingin di edit
@endsection
@section('content')

<div class="row">
  <div class="col-md-6">
    <form action="/barang/{{$barang->id}}" method="POST">
      @csrf
      <input type="hidden" name="_method" value="patch">
      <div class="mb-3">
        <label for="nama" class="form-label">Nama Barang</label>
        <input type="text" class="form-control" name="nama" id="nama" value="{{$barang->nama}}" required>
      </div>
      
      <div class="mb-3">
        <label for="stok" class="form-label">Stok</label>
        <input type="number" class="form-control" id="stok" name="stok" value="{{$barang->stok}}" required>
      </div>

      <div class="mb-3">
        <label for="jenis_barang" class="form-label">Jenis Barang</label>
        <select name="jenis_barang" id="jenis_barang" class="form-control" required>
          <option value="">Pilih Jenis Barang</option>
          @foreach ($jenis as $id => $item)
          <option value="{{$id}}"
          @if ($item == $barang->jenis_barang)
              selected
          @endif
          >{{$item}}</option>
          @endforeach
          
        </select>
      </div>
  </div>
  <div class="modal-footer">
    <button type="submit" class="btn btn-primary">Save changes</button>
  </div>
</form>
  </table>
  </div>
</div>


    
@endsection

resources/views/content/showBarang.blade.php
@extends('template.master')
@section('title')
    Warehouse 
@endsection
@section('subTitle')
    Data Barang di toko XYZ
@endsection
@section('content')
<div class="row">
  
</div>
<div class="row">
  <div class="col-md-4">
    <div class="card" >
      <div class="card-body">
        <h5 class="card-title">{{$barang->nama}}</h5>
        <h6 class="card-title mb-2">Stok : {{$barang->stok}}</h6>
        <p class="card-text">Jenis Barang : {{$barang->jenis_barang}}</p>
        <a href="/barang" class="card-link">Tampilkan semua barang</a>
        <a href="/" class="card-link">Kembali</a>
      </div>
    </div>
  </div>
</div>


    
@endsection

resources/views/content/transaksiBarang.blade.php
@extends('template.master')
@section('title')
    Penjualan 
@endsection
@section('subTitle')
    Penjualan Barang di toko XYZ antara tanggal <b>{{date('d-m-Y', strtotime($from))}}</b> hingga <b>{{date('d-m-Y', strtotime($until))}}</b> 
@endsection
@section('content')
<div class="row">
  <div class="col-md-12">
    <table class="table table-hover">
      <thead>
          <tr>
            <th scope="col">#</th>            
            <th scope="col">nama barang</th>
            <th scope="col">Stok</th>
            <th scope="col">Jumlah Transaksi</th>
            <th scope="col">Jumlah Terjual</th>
          </tr>
        </thead>
        <tbody>
            @foreach ($barang as $item)
            <tr>
                <th scope="row">{{ $loop->iteration }}</th>
                <td>{{$item->nama}}</td>
                <td>{{$item->stok}}</td>
                <td>{{$item->transaksi_count}}</td>
                <td>{{$item->sum}}</td>
                
                
                
              </tr>
            @endforeach
        </tbody>
  </table>
  </div>
</div>
<div class="row">
  <div class="col-12 mt-3">
    {{ $barang->links() }}
  </div>
  
</div>

<!-- Modal -->
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Tambah Data baru</h5>
        <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
      </div>
      <div class="modal-body">
        {{-- form --}}
        <form action="/barang" method="POST">
          @csrf
          <div class="mb-3">
            <label for="nama" class="form-label">Nama Barang</label>
            <input type="text" class="form-control" name="nama" id="nama" required>
          </div>
          
          <div class="mb-3">
            <label for="stok" class="form-label">Stok</label>
            <input type="number" class="form-control" id="stok" name="stok" required>
          </div>

          <div class="mb-3">
            <label for="jenis_barang" class="form-label">Jenis Barang</label>
            <select name="jenis_barang" id="jenis_barang" class="form-control" required>
              <option value="">Pilih Jenis Barang</option>
              <option value="1">Konsumsi</option>
              <option value="2">Pembersih</option>
            </select>
          </div>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
        <button type="submit" class="btn btn-primary">Submit</button>
      </div>
    </form>
    </div>
  </div>
</div>
    
@endsection